// Writes src/f2l/searched.ts: every alg the F2L finder's search could give, computed once (search.ts, ownside.ts) so the
// app only looks them up. For every slot, case and AUF the finder can show (the lookup's), the fewest R/L/U turns
// keeping every slot the pair is not in; for every set of those slots left open, the fewest turns through them
// (R/L/U, or with D when that is shorter) when that beats keeping them; and the own-side alg (R/U or L/U only, never
// lifting the neighbouring pair). Algs are as done from the position, AUF included.
//
//   npx vite-node scripts/f2l-searched.ts        (~10 s; rerun when search.ts, ownside.ts or data.ts change)
import { writeFileSync } from 'node:fs';
import { moveCount } from '../src/cube/alg';
import { state } from '../src/cube/state';
import { DATA } from '../src/f2l/data';
import { fullAlg, invert, SLOTS, slotSolved } from '../src/f2l/model';
import { ownSideAlg } from '../src/f2l/ownside';
import { occupiedSlots, placedIn, RLUD, shortestAlgs } from '../src/f2l/search';

const t0 = performance.now();
const out: Record<string, string> = {};
for (const slot of SLOTS) {
  const seen = new Set<string>();
  for (const hit of Object.values(DATA.slots[slot].lookup)) {
    const key = `${slot}${hit.n}|${hit.auf}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const c = DATA.slots[slot].cases[hit.n]!;
    const pair = placedIn(state(invert(fullAlg(hit.auf, c.algs[0]!))), slot);
    const others = SLOTS.filter((s) => s !== slot && !occupiedSlots(slot, c).includes(s));
    const all = shortestAlgs(pair, others)[0]!;
    out[key] = all;
    const picture = invert(all);
    const own = ownSideAlg(state(picture), slot);
    if (own?.alg) out[`${key}|own`] = own.alg;
    for (let m = 1; m < 1 << others.length; m++) {
      const open = others.filter((_, i) => m & (1 << i)), keep = others.filter((s) => !open.includes(s));
      const n = moveCount(all);
      const rlu = shortestAlgs(pair, keep, { maxDepth: n - 1 })[0];
      const d = shortestAlgs(pair, keep, { moves: RLUD, maxDepth: (rlu ? moveCount(rlu) : n) - 1 })[0];
      const best = d ?? rlu;
      if (!best) continue;
      const end = state(`${picture} ${best}`);
      const free = open.filter((s) => !slotSolved(end, s));
      if (free.length) out[`${key}|${[...keep].sort().join('.')}`] = `${best};${free.join('.')}`;
    }
  }
}
const lines = Object.entries(out).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
writeFileSync(new URL('../src/f2l/searched.ts', import.meta.url), `// Generated by scripts/f2l-searched.ts from search.ts and ownside.ts - do not edit; regenerate.
// Key: slot + case number | the lookup's AUF [| the solved slots kept, sorted, '.'-joined, for a shortcut through the
// rest | own]. Value: the alg as done from the position, AUF included; a shortcut adds ';' and the slots it leaves
// changed. A bare key is the fewest R/L/U turns keeping every slot the pair is not in.
export const SEARCHED: Record<string, string> = {
${lines.join('\n')}
};
`);
console.log(`${lines.length} entries in ${((performance.now() - t0) / 1000).toFixed(1)} s`);
